# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Archive_app2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1851, 1004)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 2101, 951))
        self.tabWidget.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: black;\n"
    "color:white;"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    border-radius:15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"    font-size:15px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"\n}"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/qss_icons/DarkOrange/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"font-size:20px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab1)
        self.tabWidget_2.setGeometry(QtCore.QRect(-30, -50, 2091, 1091))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(2091, 1091))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(2091, 16777215))
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_2Page1 = QtWidgets.QWidget()
        self.tabWidget_2Page1.setObjectName("tabWidget_2Page1")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_23.setGeometry(QtCore.QRect(100, 410, 231, 31))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_24.setGeometry(QtCore.QRect(100, 80, 231, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_31 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_31.setGeometry(QtCore.QRect(100, 370, 81, 31))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_32.setGeometry(QtCore.QRect(170, 770, 101, 31))
        self.label_32.setObjectName("label_32")
        self.comboBox_9 = QtWidgets.QComboBox(self.tabWidget_2Page1)
        self.comboBox_9.setGeometry(QtCore.QRect(400, 570, 131, 31))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_25.setGeometry(QtCore.QRect(370, 160, 231, 31))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_33 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_33.setGeometry(QtCore.QRect(370, 40, 181, 31))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_34.setGeometry(QtCore.QRect(170, 630, 71, 51))
        self.label_34.setObjectName("label_34")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_26.setGeometry(QtCore.QRect(100, 320, 231, 31))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tabWidget_2Page1)
        self.dateEdit_3.setGeometry(QtCore.QRect(400, 700, 131, 31))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 240, 231, 31))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_35 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_35.setGeometry(QtCore.QRect(100, 200, 61, 31))
        self.label_35.setObjectName("label_35")
        self.comboBox_10 = QtWidgets.QComboBox(self.tabWidget_2Page1)
        self.comboBox_10.setGeometry(QtCore.QRect(400, 780, 131, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_28.setGeometry(QtCore.QRect(370, 320, 231, 31))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_29.setGeometry(QtCore.QRect(370, 80, 231, 31))
        self.lineEdit_29.setMaxLength(10)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_36 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_36.setGeometry(QtCore.QRect(170, 560, 61, 51))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_37.setGeometry(QtCore.QRect(100, 280, 81, 31))
        self.label_37.setObjectName("label_37")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_30.setGeometry(QtCore.QRect(100, 160, 231, 31))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.comboBox_11 = QtWidgets.QComboBox(self.tabWidget_2Page1)
        self.comboBox_11.setGeometry(QtCore.QRect(400, 500, 131, 31))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.label_38 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_38.setGeometry(QtCore.QRect(370, 280, 81, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_39.setGeometry(QtCore.QRect(370, 200, 91, 31))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_40.setGeometry(QtCore.QRect(170, 710, 61, 31))
        self.label_40.setObjectName("label_40")
        self.comboBox_12 = QtWidgets.QComboBox(self.tabWidget_2Page1)
        self.comboBox_12.setGeometry(QtCore.QRect(400, 640, 131, 31))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_41 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_41.setGeometry(QtCore.QRect(370, 370, 111, 31))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_42.setGeometry(QtCore.QRect(100, 120, 121, 31))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_43.setGeometry(QtCore.QRect(170, 500, 151, 31))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_44.setGeometry(QtCore.QRect(370, 120, 211, 31))
        self.label_44.setObjectName("label_44")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_31.setGeometry(QtCore.QRect(100, 240, 231, 31))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_32.setGeometry(QtCore.QRect(370, 410, 231, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_45 = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label_45.setGeometry(QtCore.QRect(100, 40, 51, 31))
        self.label_45.setObjectName("label_45")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tabWidget_2Page1)
        self.tableWidget_3.setGeometry(QtCore.QRect(770, 210, 1161, 711))
        self.tableWidget_3.setStyleSheet("")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(15)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tabWidget_2Page1)
        self.lineEdit_33.setGeometry(QtCore.QRect(1310, 100, 271, 51))
        self.lineEdit_33.setStyleSheet("color:black;\n"
"font-size:15px;")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_9 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_9.setGeometry(QtCore.QRect(1630, 100, 171, 51))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_10.setGeometry(QtCore.QRect(200, 850, 211, 61))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_11.setGeometry(QtCore.QRect(790, 100, 161, 51))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_12.setGeometry(QtCore.QRect(1020, 100, 161, 51))
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget_2.addTab(self.tabWidget_2Page1, "")
        self.tabWidget_2Page2 = QtWidgets.QWidget()
        self.tabWidget_2Page2.setObjectName("tabWidget_2Page2")
        self.tabWidget_2.addTab(self.tabWidget_2Page2, "")
        self.tabWidget.addTab(self.tab1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1851, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuview = QtWidgets.QMenu(self.menubar)
        self.menuview.setObjectName("menuview")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_app = QtWidgets.QAction(MainWindow)
        self.actionAbout_app.setObjectName("actionAbout_app")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLight_ode = QtWidgets.QAction(MainWindow)
        self.actionLight_ode.setObjectName("actionLight_ode")
        self.menuFile.addAction(self.actionAbout_app)
        self.menuFile.addAction(self.actionsave)
        self.menuFile.addAction(self.actionExit)
        self.menuview.addAction(self.actionLight_ode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuview.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_31.setText(_translate("MainWindow", "Region"))
        self.label_32.setText(_translate("MainWindow", "Martial Status"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Female"))
        self.label_33.setText(_translate("MainWindow", "Lastname"))
        self.label_34.setText(_translate("MainWindow", "Study"))
        self.label_35.setText(_translate("MainWindow", "Email"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Single"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "maried"))
        self.label_36.setText(_translate("MainWindow", "Gender"))
        self.label_37.setText(_translate("MainWindow", "Country"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Sick"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Not sick"))
        self.label_38.setText(_translate("MainWindow", "City"))
        self.label_39.setText(_translate("MainWindow", "Phonenumber"))
        self.label_40.setText(_translate("MainWindow", "Birthday"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Collage"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "School"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "Akadimy"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "University"))
        self.label_41.setText(_translate("MainWindow", "Native Languages"))
        self.label_42.setText(_translate("MainWindow", "Mother name"))
        self.label_43.setText(_translate("MainWindow", "Pathological condition"))
        self.label_44.setText(_translate("MainWindow", "Father name"))
        self.label_45.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mother name"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Father Name"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Phonenumber"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Region"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Native Language"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Pathology"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Study"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Martial Status"))
        self.lineEdit_33.setPlaceholderText(_translate("MainWindow", "Search For Item"))
        self.pushButton_9.setText(_translate("MainWindow", "Search Now"))
        self.pushButton_10.setText(_translate("MainWindow", "Save"))
        self.pushButton_11.setText(_translate("MainWindow", "Change"))
        self.pushButton_12.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "INFO"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuview.setTitle(_translate("MainWindow", "Mode"))
        self.actionAbout_app.setText(_translate("MainWindow", "About app"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLight_ode.setText(_translate("MainWindow", "Light Mode"))
